# https://code.visualstudio.com/docs/devcontainers/create-dev-container#_extend-your-docker-compose-file-for-development

services:
  dotnet-sdk-with-karate:
      # Note that the path of the Dockerfile and context is relative to the *primary*
      # docker-compose.yml file (the first in the devcontainer.json "dockerComposeFile"
      # array). The sample below assumes your primary file is in the root of your project.
      build:
        context: .
        dockerfile: .devcontainer/Dockerfile
      # Mounts the project folder to '/workspaces/inner-circle-items-api'. While this file is in .devcontainer,
      # mounts are relative to the first file in the list, which is a level up.
      volumes:
        - ${LOCAL_WORKSPACE_FOLDER:-./}:/workspaces/inner-circle-items-api

      # Overrides default command so things don't shut down after the process ends.
      command: sleep infinity

      # this is needed so that we can access the API at localhost if we run it from this Dev Container
      # this also allows API that is started from Dev Container using dotnet run to access DB at localhost
      network_mode: "host"

      # it is needed for GitHub codespaces or Ubuntu (probably) to add missing host.docker.internal that is part of Docker Desktop (macOS, Windows)
      # proposed by AI Overview
      extra_hosts:
        - ${EXTRA_HOST_FOR_CODESPACES:-myhostv6=::1}

      environment:
        EXTRA_HOST_FOR_CODESPACES: ${CODESPACES:+host.docker.internal:host-gateway}
