name: Publish Docker image

# !!! NEVER add on push when there is on workflow_call
# if you do that the workflow can run multiple times
# for instance if you re-use this docker build workflow for prod deployment and for local-env in PR
# it will build the docker image it twice
# if you build => deploy => run e2e against prod it will build the image 3 times!
on:
  # to allow to wait for a docker image to be published to proceed in another workflow
  workflow_call:

jobs:
  push_to_registry:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # this is needed to address this issue according to the comment https://github.com/devcontainers/ci/issues/271#issuecomment-2301764487
      # otherwise our TourmalineCore org name cannot be used in docker image names, only tourmalinecore
      - name: Add Registry Image Env Var With Lowercase Organization and Repo Name
        run: |
          echo "REGISTRY_IMAGE=ghcr.io/${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}
          tags: |
            # minimal (short sha)
            type=sha
            # full length sha
            type=sha,format=long
            # SemVer human readable version for default branch
            type=raw,value=${{ env.SEMVER_VERSION }},enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
            # set latest tag for default branch
            # https://github.com/docker/metadata-action/issues/171 explains how to tag latest only on default branch
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
        env:
          # https://github.com/docker/metadata-action/issues/283
          # without this flag it won't tag the image using the commit SHA 
          # for non push events like pull_request ones it requires this :(
          DOCKER_METADATA_PR_HEAD_SHA: true

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Api/Dockerfile
          build-args: |
            EXCLUDE_UNIT_TESTS_FROM_BUILD=true
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
