name: Lint

on:
  push:
    branches:
      - feature/*

jobs:
  unit-tests:
    name: Run linting
    runs-on: ubuntu-24.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4 

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Check there are no non-formatted files
        run: dotnet format --verify-no-changes
